# Cloudflare Worker configuration file
name = "form-submission-handler"
main = "simple-worker.js"
compatibility_date = "2024-01-01"

# Environment variables (optional)
[vars]
ENVIRONMENT = "production"

# Routes (optional - you can also use custom domains)
# routes = [
#   { pattern = "your-domain.com/api/submit", zone_name = "your-domain.com" }
# ]

# Cron triggers (optional - for cleanup tasks)
# [triggers]
# crons = ["0 0 * * *"]  # Daily at midnight 